Ros2 devel
husarion/panther_simulation pull request #2
Opened 2022-10-07 20:50 UTC by Kotochleb

2022-10-10 13:15 UTC, KmakD requested changes
I don't know if all of this apply to this PR but there are few things:
- Python scripts does not follow coding style 
- Includes are not in alphabetical order
- Dockerfile is a mess

2022-10-10 13:15 UTC, KmakD commented on panther_gazebo/panther_gazebo/launch/panther.launch.py
> +  wheel_config_path = LaunchConfiguration('wheel_config_path', default=os.path.join(panther_description_config_path, 'WH04.yaml'))
```suggestion
  wheel_config_path = LaunchConfiguration('wheel_config_path', default=os.path.join(panther_description_config_path, 'WH01.yaml'))
```
I guess WH01 should be default

2022-10-10 13:15 UTC, KmakD commented on panther_gazebo/panther_gazebo/package.xml
> +  <url type="repository">https://github.com/husarion/panther_description/tree/ros2</url>
In other repos "repository" is before "bugtracker"

2022-10-10 13:15 UTC, KmakD commented on panther_gazebo/panther_gazebo/package.xml
> +  <exec_depend>gazebo_plugins</exec_depend>
Packages not in alphabetical order

2022-10-12 14:31 UTC, Kotochleb commented on panther_gazebo/panther_gazebo/launch/panther.launch.py
> +  wheel_config_path = LaunchConfiguration('wheel_config_path', default=os.path.join(panther_description_config_path, 'WH04.yaml'))
Yeah. My bad

2022-10-12 14:31 UTC, Kotochleb commented on panther_gazebo/panther_gazebo/package.xml
> +  <url type="repository">https://github.com/husarion/panther_description/tree/ros2</url>
Done

2022-10-12 14:31 UTC, Kotochleb commented on panther_gazebo/panther_gazebo/package.xml
> +  <exec_depend>gazebo_plugins</exec_depend>
Done

2022-10-12 15:51 UTC, Kotochleb commented
> I don't know if all of this apply to this PR but there are few things:
> 
>     * Python scripts does not follow coding style
> 
>     * Includes are not in alphabetical order
> 
>     * Dockerfile is a mess

We will move all those changes to new task and new PR in the next sprint

2022-10-13 12:39 UTC, KmakD requested changes

2022-10-13 12:39 UTC, KmakD commented on panther_gazebo/panther_gazebo/package.xml
> +  <depend>gazebo_ros</depend>depend
```suggestion
  <depend>gazebo_ros</depend>
```

2022-10-18 07:30 UTC, KmakD approved these changes

2022-10-18 07:30 UTC, merged